// Generated by CoffeeScript 1.6.3
(function() {
  var AbstractPusher, BocoError;

  BocoError = require('boco-error');

  module.exports = AbstractPusher = (function() {
    function AbstractPusher() {}

    AbstractPusher.prototype.push = function(command, callback) {
      throw new BocoError.NotImplemented();
    };

    return AbstractPusher;

  })();

}).call(this);

/*
//@ sourceMappingURL=AbstractPusher.map
*/
