// Generated by CoffeeScript 1.6.3
(function() {
  var AddItem, BocoCommand, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BocoCommand = require('boco-command');

  AddItem = (function(_super) {
    __extends(AddItem, _super);

    function AddItem() {
      _ref = AddItem.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AddItem.prototype.setParameters = function(params) {
      if (params == null) {
        params = {};
      }
      return this.parameters = {
        url: params.url,
        mimeType: params.mimeType,
        name: params.name
      };
    };

    AddItem.prototype.validateParameters = function() {
      var p, v, validation;
      v = validation = AddItem.__super__.validateParameters.call(this);
      p = this.parameters;
      if (p.url == null) {
        v.addError('url', 'must be present');
      }
      if (p.mimeType == null) {
        v.addError('mimeType', 'must be present');
      }
      if (p.name == null) {
        v.addError('name', 'must be present');
      }
      return validation;
    };

    return AddItem;

  })(BocoCommand.Command);

  module.exports = AddItem;

}).call(this);

/*
//@ sourceMappingURL=AddItem.map
*/
