// Generated by CoffeeScript 1.6.3
(function() {
  var CommandWorkerService, ItemAdded, ResourceTypes;

  ResourceTypes = require('./ResourceTypes');

  ItemAdded = require('./ItemAdded');

  module.exports = CommandWorkerService = (function() {
    function CommandWorkerService(props) {
      if (props == null) {
        props = {};
      }
      this.sourced = props.sourced;
    }

    CommandWorkerService.prototype.addItem = function(command, callback) {
      var itemAdded, params, revision;
      params = command.parameters;
      revision = this.sourced.createRevision(ResourceTypes.LibraryItem);
      itemAdded = new ItemAdded({
        url: params.url,
        mimeType: params.mimeType,
        name: params.name
      });
      revision.addEvent(ItemAdded.name, itemAdded);
      return this.sourced.storeRevision(revision, function(error) {
        return callback(error);
      });
    };

    return CommandWorkerService;

  })();

}).call(this);

/*
//@ sourceMappingURL=CommandWorkerService.map
*/
