// Generated by CoffeeScript 1.6.3
(function() {
  var ItemAdded;

  module.exports = ItemAdded = (function() {
    function ItemAdded(props) {
      if (props == null) {
        props = {};
      }
      this.url = props.url;
      this.mimeType = props.mimeType;
      this.name = props.name;
    }

    return ItemAdded;

  })();

}).call(this);

/*
//@ sourceMappingURL=ItemAdded.map
*/
