// Generated by CoffeeScript 1.6.3
(function() {
  var CustomError, NotImplemented, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CustomError = require('./CustomError');

  module.exports = NotImplemented = (function(_super) {
    __extends(NotImplemented, _super);

    function NotImplemented() {
      _ref = NotImplemented.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    NotImplemented.prototype.setDefaults = function() {
      this.message = "not implemented.";
      return NotImplemented.__super__.setDefaults.apply(this, arguments);
    };

    return NotImplemented;

  })(CustomError);

}).call(this);

/*
//@ sourceMappingURL=NotImplemented.map
*/
