// Generated by CoffeeScript 1.6.3
(function() {
  var ResourceTypes, exports;

  ResourceTypes = exports = {
    LibraryItem: "LibraryItem"
  };

}).call(this);

/*
//@ sourceMappingURL=ResourceTypes.map
*/
